server:
  port: ${PORT:8080}

  gemini:
  api-key: ${GEMINI_API_KEY}

openai:
  api-key: ${OPENAI_API_KEY}

openrouter:
  api-key: ${OPENROUTER_API_KEY}

deepseek:
  api-key: ${DEEPSEEK_API_KEY}

grok:
  api-key: ${GROK_API_KEY}
