package com.algomind.model;

import com.algomind.timeline.ExecutionTimeline;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ExecutionSession {
    
    private String sessionId;
    private String algorithmName;
    private int currentStep;
    private int totalSteps;
    private PlaybackStatus playbackStatus;
    private double playbackSpeed;
    private LocalDateTime createdAt;
    
    // Internal state: holds the full timeline generated by ExecutionEngine
    private ExecutionTimeline executionTimeline;
}
